#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

# For future updates see http://downloads.mariadb.org/mariadb/repositories/
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8

# First remove this repo to avoid duplication.
sudo add-apt-repository -r 'deb [arch=amd64,i386,ppc64el] http://mirror.daniel-jost.net/mariadb/repo/10.1/ubuntu xenial main'
sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirror.daniel-jost.net/mariadb/repo/10.1/ubuntu xenial main'
sudo apt update
sudo apt install mariadb-server

sudo mysql_secure_installation
