#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

sudo add-apt-repository ppa:ondrej/php
sudo apt update

for VERSION in ${PHP_VERSIONS[@]}
do
  sudo apt install php$VERSION php$VERSION-fpm php$VERSION-curl php$VERSION-gd \
                   php$VERSION-mbstring php$VERSION-mysql php$VERSION-xml
done

sudo apt install php-pear php-uploadprogress php-xdebug
