#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install php7.0 php7.0-fpm php7.0-curl php7.0-gd php7.0-mbstring php7.0-mysql php7.0-xml \
                 php5.6 php5.6-fpm php5.6-curl php5.6-gd php5.6-mbstring php5.6-mysql php5.6-xml \
                 php-pear php-uploadprogress
