#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

sudo add-apt-repository ppa:ondrej/apache2
sudo apt update
sudo apt install apache2

sudo a2enmod headers rewrite proxy_fcgi setenvif
# @TODO FPM for other PHP versions and per-VHost.
sudo a2enconf php7.0-fpm
sudo systemctl restart apache2
