#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

if [ ! -f "/usr/local/bin/composer" ]
then
  TMP=`mktemp -d`

  # For future updates see https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
  EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
  php -r "copy('https://getcomposer.org/installer', '$TMP/composer-setup.php');"
  ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', '$TMP/composer-setup.php');")

  if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
  then
    echo "Invalid Composer installer signature!"
    rm -rf $TMP
    exit 1
  fi

  if ! php $TMP/composer-setup.php --install-dir=$TMP
  then
    echo "Unable to setup Composer!"
    exit 1
  fi

  rm $TMP/composer-setup.php

  if ! sudo mv $TMP/composer.phar /usr/local/bin/composer
  then
    echo "Unable to move Composer to /usr/local/bin/composer !"
    exit 1
  fi

  rm -rf $TMP
fi

if ! grep -q "COMPOSER_PROCESS_TIMEOUT" ~/.bashrc
then
  echo "export COMPOSER_PROCESS_TIMEOUT=31536000" >> ~/.bashrc
fi

if ! grep -q "COMPOSER_SORT_PACKAGES" ~/.bashrc
then
  echo "export COMPOSER_SORT_PACKAGES=true" >> ~/.bashrc
fi

if ! grep -q "\$HOME/.config/composer/vendor/bin" ~/.profile
then
  echo "PATH=\"\$HOME/.config/composer/vendor/bin:\$PATH\"" >> ~/.profile
fi

composer global require "hirak/prestissimo:^0.3"
composer global require consolidation/cgr

if ! grep -q "CGR_BASE_DIR" ~/.bashrc
then
  echo "export CGR_BASE_DIR=\"\$HOME/.config/composer/global\"" >> ~/.bashrc
fi

if ! grep -q "CGR_BIN_DIR" ~/.bashrc
then
  echo "export CGR_BIN_DIR=\"\$HOME/.config/composer/vendor/bin\"" >> ~/.bashrc
fi
