#!/bin/bash

source "$(dirname "$0")/000-common"
source "$(dirname "$0")/000-config"

SRC="/usr/local/src"
BIN="/usr/local/bin"

# For future updates see https://github.com/klausi/pareviewsh
sudo git clone --branch master https://github.com/lucasdemarchi/codespell.git $SRC/codespell
sudo git clone https://github.com/klausi/pareviewsh.git $SRC/pareviewsh

sudo ln -fs $SRC/codespell/bin/codespell $BIN/codespell
sudo ln -fs $SRC/pareviewsh/pareview.sh $BIN
